"""empty message

Revision ID: 3a3393c59bd2
Revises: 80dc9b1d3b74
Create Date: 2021-12-05 21:00:17.167173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3393c59bd2'
down_revision = '80dc9b1d3b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
