"""empty message

Revision ID: 68fafa96e5f2
Revises: 3a3393c59bd2
Create Date: 2021-12-07 22:25:58.036576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fafa96e5f2'
down_revision = '3a3393c59bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('langx', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('langx')

    # ### end Alembic commands ###
